development:
  # bucket: paperclip.tabirepo.com
  # bucket: tabirepo.tk
  bucket: dev.paperclip.tabi-repo.net
  access_key_id: AKIAJJS7KV3CHQE5OZOQ
  secret_access_key: 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
  s3_host_name: s3-website-ap-northeast-1.amazonaws.com
  # s3_host_name: paperclip.tabirepo.com.s3-website-ap-northeast-1.amazonaws.com

production:
  bucket: paperclip.tabi-repo.net
  access_key_id: AKIAJJS7KV3CHQE5OZOQ
  secret_access_key: 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
  s3_host_name: s3-website-ap-northeast-1.amazonaws.com
  # s3_host_name: paperclip.tabirepo.com.s3-website-ap-northeast-1.amazonaws.com
